# This workflow builds JSDoc documentation and publishes it to
# GitHub pages
name: GitHub pages

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTION: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: npm ci
      - run: npm site

      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./_site